name: Build
on:
    push:
jobs:
    build-project:
        strategy:
            matrix:
                type: [ Debug, Release ]
                os: [ ubuntu-latest ]

        name: Build Project
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4.1.1

            # Install required cross-gen tools and QEMU.
            -   uses: awalsh128/cache-apt-pkgs-action@latest
                with:
                    packages: crossbuild-essential-arm64 qemu-system-arm
                    version: 1.0

            # Use CCache to cache compilation results.
            -   name: ccache
                uses: hendrikmuhs/ccache-action@v1.2

            -   name: Configure Project
                run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_CHECKS=ON -DGCC_PREFIX=aarch64-linux-gnu- -DGCC_SUFFIX= -DCMAKE_BUILD_TYPE=${{matrix.type}} -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache

            -   name: Build Project
                run: make -j -C ${{github.workspace}}/build

            # - name: Test Project
            #  runs: ctest --test-dir build
