name: Build
on:
    push:
jobs:
    build-project:
        strategy:
            matrix:
                type: [ Debug, Release ]
                os: [ ubuntu-latest ]

        name: Build Project
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4.1.1

            -   name: Add PPT for GCC-13
                run: sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa

            -   name: Update System
                run: sudo apt update

            # Install required cross-gen tools and QEMU.
            -   uses: awalsh128/cache-apt-pkgs-action@latest
                with:
                    packages: gcc-13-aarch64-linux-gnu g++-13-aarch64-linux-gnu qemu-system-arm ccache
                    version: 1.0

            # Use CCache to cache compilation results.
            -   name: ccache
                uses: hendrikmuhs/ccache-action@v1.2
                with:
                    key: ${{github.job}}-${{matrix.os}}-${{matrix.type}}

            -   name: Configure Project
                run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.type}} -DENABLE_CHECKS=ON -DGCC_PREFIX=aarch64-linux-gnu- -DGCC_SUFFIX=-13 -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache

            -   name: Build Project
                run: make -j -C ${{github.workspace}}/build

            # - name: Test Project
            #  runs: ctest --test-dir build
