name: Build
on:
    push:
jobs:
    build-project:
        strategy:
            matrix:
                type: [ Debug, Release ]
                os: [ ubuntu-latest ]

        name: Build Project
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Download aarch64-none-elf-gcc-13
                run: wget -O /tmp/gcc.tar.xz "$GCC_URL"
                env:
                    GCC_URL: https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-aarch64-none-elf.tar.xz

            -   name: Create target directory
                run: mkdir -p /tmp/aarch64-gcc

            -   name: Extract gcc archive
                run: tar --strip-component=1 -xf /tmp/gcc.tar.xz -C /tmp/aarch64-gcc

            -   name: Setup variables
                run: echo "/tmp/aarch64-gcc/bin" >> "$GITHUB_PATH"

            -   name: GCC Version Check
                run: aarch64-none-elf-g++ --version

            -   name: CMake Version Check
                run: cmake --version

            -   name: Clang-tidy Version Check
                run: clang-tidy --version

            -   name: List included directories
                run: |
                    INC_DIRS=$(aarch64-none-elf-gcc -xc++ /dev/null -E -Wp,-v 2>&1 | sed -n 's,^ ,,p')
                    echo "Directories: \"$INC_DIRS\""
                    FINAL_DIRS=""
                    for dir in $INC_DIRS
                    do
                        FINAL_DIRS="$(realpath $dir):$FINAL_DIRS"
                    done
                    FINAL_DIRS="${FINAL_DIRS::-1}"
                    echo "Final Dirs: \"$FINAL_DIRS\""
                    echo "FINAL_DIRS=\"$FINAL_DIRS\"" >> "$GITHUB_ENV"

            -   name: Checkout
                uses: actions/checkout@v4.1.1

            # Install required cross-gen tools and QEMU.
            -   uses: awalsh128/cache-apt-pkgs-action@latest
                with:
                    packages: qemu-system-arm ccache
                    version: 1.0

            # Use CCache to cache compilation results.
            -   name: ccache
                uses: hendrikmuhs/ccache-action@v1.2
                with:
                    key: ${{github.job}}-${{matrix.os}}-${{matrix.type}}

            -   name: Configure Project
                run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.type}} -DENABLE_CHECKS=ON -DCMAKE_SYSROOT="/tmp/aarch64-gcc/aarch64-none-elf" -DGCC_PREFIX=aarch64-none-elf- -DGCC_SUFFIX= -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache

            -   name: Include Check
                run: |
                    echo "We have: $FINAL_DIRS"

            -   name: Build Project
                run: CPATH=$FINAL_DIRS make -C build VERBOSE=1


            # - name: Test Project
            #  runs: ctest --test-dir build
