name: Build
on:
    push:
jobs:
    build-project:
        strategy:
            matrix:
                type: [ Debug, Release ]
                os: [ ubuntu-latest ]

        name: Build Project
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Install aarch64-none-elf-gcc-13
                run: |
                    wget -P /tmp https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-aarch64-none-elf.tar.xz
                    tar -xf /tmp/arm-gnu-toolchain-13.2.rel1-x86_64-aarch64-none-elf.tar.xz -C /tmp
                    echo "/tmp/arm-gnu-toolchain-13.2.Rel1-x86_64-aarch64-none-elf/bin" >> $GITHUB_PATH

            -   name: GCC Version
                run: |
                    echo "$PATH"
                    aarch64-none-elf-g++ --version

            -   name: Checkout
                uses: actions/checkout@v4.1.1

            # Install required cross-gen tools and QEMU.
            -   uses: awalsh128/cache-apt-pkgs-action@latest
                with:
                    packages: qemu-system-arm ccache
                    version: 1.0

            # Use CCache to cache compilation results.
            -   name: ccache
                uses: hendrikmuhs/ccache-action@v1.2
                with:
                    key: ${{github.job}}-${{matrix.os}}-${{matrix.type}}

            -   name: Configure Project
                run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.type}} -DENABLE_CHECKS=ON -DGCC_PREFIX=aarch64-none-elf- -DGCC_SUFFIX=-13 -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache

            -   name: Build Project
                run: make -j -C ${{github.workspace}}/build

            # - name: Test Project
            #  runs: ctest --test-dir build
