name: Clang Build
on:
    push:
jobs:
    build-project:
        strategy:
            matrix:
                type: [ Debug, Release ]
                os: [ ubuntu-latest ]

        name: Build Project
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4.1.1

            -   uses: awalsh128/cache-apt-pkgs-action@latest
                with:
                    packages: qemu-system-arm g++-12-aarch64-linux-gnu gcc-12-aarch64-linux-gnu
                    version: 1.0

            -   name: Configure Project
                run: |
                    cmake -B ${{github.workspace}}/build \
                        --toolchain=cmake/ClangToolchain.cmake \
                        -DCMAKE_BUILD_TYPE=${{matrix.type}} \
                        -DENABLE_CHECKS=ON \
                        -DCLANG_SUFFIX=-15 \
                        -DCLANG_TRIPLE=aarch64-linux-gnu

            -   name: Build Project
                run: make -j -C build VERBOSE=1

            # - name: Test Project
            #  runs: ctest --test-dir build
